module.exports = {
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  DELETE_COVER_IMAGE: 'DELETE_COVER_IMAGE',
  DELETE_IMAGE: 'DELETE_IMAGE',
  DELETE_PROJECT: 'DELETE_PROJECT',
  DELETE_TEST_CASE: 'DELETE_TEST_CASE',
  DELETE_USER: 'DELETE_USER',
  FULFILL_IMAGE: 'FULFILL_IMAGE',
  INTRODUCE_COVER_IMAGE: 'INTRODUCE_COVER_IMAGE',
  INTRODUCE_IMAGE: 'INTRODUCE_IMAGE',
  INTRODUCE_PROJECT: 'INTRODUCE_PROJECT',
  INTRODUCE_TEST_CASE: 'INTRODUCE_TEST_CASE',
  INTRODUCE_USER: 'INTRODUCE_USER',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  UPDATE_TEST_CASE: 'UPDATE_TEST_CASE',
  UPDATE_USER: 'UPDATE_USER',
  SIGN_OUT: 'SIGN_OUT',
  VIEW_PROFILE: 'VIEW_PROFILE'
}
